var namespacenet_1_1minecraft_1_1entity =
[
    [ "ai", "namespacenet_1_1minecraft_1_1entity_1_1ai.html", "namespacenet_1_1minecraft_1_1entity_1_1ai" ],
    [ "boss", "namespacenet_1_1minecraft_1_1entity_1_1boss.html", "namespacenet_1_1minecraft_1_1entity_1_1boss" ],
    [ "effect", "namespacenet_1_1minecraft_1_1entity_1_1effect.html", "namespacenet_1_1minecraft_1_1entity_1_1effect" ],
    [ "item", "namespacenet_1_1minecraft_1_1entity_1_1item.html", "namespacenet_1_1minecraft_1_1entity_1_1item" ],
    [ "monster", "namespacenet_1_1minecraft_1_1entity_1_1monster.html", "namespacenet_1_1minecraft_1_1entity_1_1monster" ],
    [ "passive", "namespacenet_1_1minecraft_1_1entity_1_1passive.html", "namespacenet_1_1minecraft_1_1entity_1_1passive" ],
    [ "player", "namespacenet_1_1minecraft_1_1entity_1_1player.html", "namespacenet_1_1minecraft_1_1entity_1_1player" ],
    [ "projectile", "namespacenet_1_1minecraft_1_1entity_1_1projectile.html", "namespacenet_1_1minecraft_1_1entity_1_1projectile" ],
    [ "DataWatcher", "classnet_1_1minecraft_1_1entity_1_1_data_watcher.html", "classnet_1_1minecraft_1_1entity_1_1_data_watcher" ],
    [ "Entity", "classnet_1_1minecraft_1_1entity_1_1_entity.html", "classnet_1_1minecraft_1_1entity_1_1_entity" ],
    [ "EntityAgeable", "classnet_1_1minecraft_1_1entity_1_1_entity_ageable.html", "classnet_1_1minecraft_1_1entity_1_1_entity_ageable" ],
    [ "EntityBodyHelper", "classnet_1_1minecraft_1_1entity_1_1_entity_body_helper.html", "classnet_1_1minecraft_1_1entity_1_1_entity_body_helper" ],
    [ "EntityCreature", "classnet_1_1minecraft_1_1entity_1_1_entity_creature.html", "classnet_1_1minecraft_1_1entity_1_1_entity_creature" ],
    [ "EntityEggInfo", "classnet_1_1minecraft_1_1entity_1_1_entity_egg_info.html", "classnet_1_1minecraft_1_1entity_1_1_entity_egg_info" ],
    [ "EntityFlying", "classnet_1_1minecraft_1_1entity_1_1_entity_flying.html", "classnet_1_1minecraft_1_1entity_1_1_entity_flying" ],
    [ "EntityHanging", "classnet_1_1minecraft_1_1entity_1_1_entity_hanging.html", "classnet_1_1minecraft_1_1entity_1_1_entity_hanging" ],
    [ "EntityList", "classnet_1_1minecraft_1_1entity_1_1_entity_list.html", null ],
    [ "EntityLiving", "classnet_1_1minecraft_1_1entity_1_1_entity_living.html", "classnet_1_1minecraft_1_1entity_1_1_entity_living" ],
    [ "EntitySelectorArmoredMob", "classnet_1_1minecraft_1_1entity_1_1_entity_selector_armored_mob.html", "classnet_1_1minecraft_1_1entity_1_1_entity_selector_armored_mob" ],
    [ "EntityTracker", "classnet_1_1minecraft_1_1entity_1_1_entity_tracker.html", "classnet_1_1minecraft_1_1entity_1_1_entity_tracker" ],
    [ "EntityTrackerEntry", "classnet_1_1minecraft_1_1entity_1_1_entity_tracker_entry.html", "classnet_1_1minecraft_1_1entity_1_1_entity_tracker_entry" ],
    [ "EnumCreatureAttribute", "enumnet_1_1minecraft_1_1entity_1_1_enum_creature_attribute.html", "enumnet_1_1minecraft_1_1entity_1_1_enum_creature_attribute" ],
    [ "EnumCreatureType", "enumnet_1_1minecraft_1_1entity_1_1_enum_creature_type.html", "enumnet_1_1minecraft_1_1entity_1_1_enum_creature_type" ],
    [ "EnumEntitySize", "enumnet_1_1minecraft_1_1entity_1_1_enum_entity_size.html", "enumnet_1_1minecraft_1_1entity_1_1_enum_entity_size" ],
    [ "IEntityMultiPart", "interfacenet_1_1minecraft_1_1entity_1_1_i_entity_multi_part.html", "interfacenet_1_1minecraft_1_1entity_1_1_i_entity_multi_part" ],
    [ "IMerchant", "interfacenet_1_1minecraft_1_1entity_1_1_i_merchant.html", "interfacenet_1_1minecraft_1_1entity_1_1_i_merchant" ],
    [ "INpc", "interfacenet_1_1minecraft_1_1entity_1_1_i_npc.html", null ],
    [ "IProjectile", "interfacenet_1_1minecraft_1_1entity_1_1_i_projectile.html", "interfacenet_1_1minecraft_1_1entity_1_1_i_projectile" ],
    [ "IRangedAttackMob", "interfacenet_1_1minecraft_1_1entity_1_1_i_ranged_attack_mob.html", "interfacenet_1_1minecraft_1_1entity_1_1_i_ranged_attack_mob" ],
    [ "NpcMerchant", "classnet_1_1minecraft_1_1entity_1_1_npc_merchant.html", "classnet_1_1minecraft_1_1entity_1_1_npc_merchant" ],
    [ "WatchableObject", "classnet_1_1minecraft_1_1entity_1_1_watchable_object.html", "classnet_1_1minecraft_1_1entity_1_1_watchable_object" ]
];