var namespacenet_1_1minecraft_1_1world =
[
    [ "biome", "namespacenet_1_1minecraft_1_1world_1_1biome.html", "namespacenet_1_1minecraft_1_1world_1_1biome" ],
    [ "chunk", "namespacenet_1_1minecraft_1_1world_1_1chunk.html", "namespacenet_1_1minecraft_1_1world_1_1chunk" ],
    [ "demo", "namespacenet_1_1minecraft_1_1world_1_1demo.html", "namespacenet_1_1minecraft_1_1world_1_1demo" ],
    [ "gen", "namespacenet_1_1minecraft_1_1world_1_1gen.html", "namespacenet_1_1minecraft_1_1world_1_1gen" ],
    [ "storage", "namespacenet_1_1minecraft_1_1world_1_1storage.html", "namespacenet_1_1minecraft_1_1world_1_1storage" ],
    [ "ChunkCache", "classnet_1_1minecraft_1_1world_1_1_chunk_cache.html", "classnet_1_1minecraft_1_1world_1_1_chunk_cache" ],
    [ "ChunkCoordIntPair", "classnet_1_1minecraft_1_1world_1_1_chunk_coord_int_pair.html", "classnet_1_1minecraft_1_1world_1_1_chunk_coord_int_pair" ],
    [ "ChunkPosition", "classnet_1_1minecraft_1_1world_1_1_chunk_position.html", "classnet_1_1minecraft_1_1world_1_1_chunk_position" ],
    [ "ColorizerFoliage", "classnet_1_1minecraft_1_1world_1_1_colorizer_foliage.html", null ],
    [ "ColorizerGrass", "classnet_1_1minecraft_1_1world_1_1_colorizer_grass.html", null ],
    [ "EnumGameType", "enumnet_1_1minecraft_1_1world_1_1_enum_game_type.html", "enumnet_1_1minecraft_1_1world_1_1_enum_game_type" ],
    [ "EnumSkyBlock", "enumnet_1_1minecraft_1_1world_1_1_enum_sky_block.html", "enumnet_1_1minecraft_1_1world_1_1_enum_sky_block" ],
    [ "Explosion", "classnet_1_1minecraft_1_1world_1_1_explosion.html", "classnet_1_1minecraft_1_1world_1_1_explosion" ],
    [ "GameRules", "classnet_1_1minecraft_1_1world_1_1_game_rules.html", "classnet_1_1minecraft_1_1world_1_1_game_rules" ],
    [ "IBlockAccess", "interfacenet_1_1minecraft_1_1world_1_1_i_block_access.html", "interfacenet_1_1minecraft_1_1world_1_1_i_block_access" ],
    [ "IWorldAccess", "interfacenet_1_1minecraft_1_1world_1_1_i_world_access.html", "interfacenet_1_1minecraft_1_1world_1_1_i_world_access" ],
    [ "MinecraftException", "classnet_1_1minecraft_1_1world_1_1_minecraft_exception.html", "classnet_1_1minecraft_1_1world_1_1_minecraft_exception" ],
    [ "NextTickListEntry", "classnet_1_1minecraft_1_1world_1_1_next_tick_list_entry.html", "classnet_1_1minecraft_1_1world_1_1_next_tick_list_entry" ],
    [ "PortalPosition", "classnet_1_1minecraft_1_1world_1_1_portal_position.html", "classnet_1_1minecraft_1_1world_1_1_portal_position" ],
    [ "SpawnerAnimals", "classnet_1_1minecraft_1_1world_1_1_spawner_animals.html", null ],
    [ "Teleporter", "classnet_1_1minecraft_1_1world_1_1_teleporter.html", "classnet_1_1minecraft_1_1world_1_1_teleporter" ],
    [ "World", "classnet_1_1minecraft_1_1world_1_1_world.html", "classnet_1_1minecraft_1_1world_1_1_world" ],
    [ "WorldManager", "classnet_1_1minecraft_1_1world_1_1_world_manager.html", "classnet_1_1minecraft_1_1world_1_1_world_manager" ],
    [ "WorldProvider", "classnet_1_1minecraft_1_1world_1_1_world_provider.html", "classnet_1_1minecraft_1_1world_1_1_world_provider" ],
    [ "WorldProviderEnd", "classnet_1_1minecraft_1_1world_1_1_world_provider_end.html", "classnet_1_1minecraft_1_1world_1_1_world_provider_end" ],
    [ "WorldProviderHell", "classnet_1_1minecraft_1_1world_1_1_world_provider_hell.html", "classnet_1_1minecraft_1_1world_1_1_world_provider_hell" ],
    [ "WorldProviderSurface", "classnet_1_1minecraft_1_1world_1_1_world_provider_surface.html", "classnet_1_1minecraft_1_1world_1_1_world_provider_surface" ],
    [ "WorldSavedData", "classnet_1_1minecraft_1_1world_1_1_world_saved_data.html", "classnet_1_1minecraft_1_1world_1_1_world_saved_data" ],
    [ "WorldServer", "classnet_1_1minecraft_1_1world_1_1_world_server.html", "classnet_1_1minecraft_1_1world_1_1_world_server" ],
    [ "WorldServerMulti", "classnet_1_1minecraft_1_1world_1_1_world_server_multi.html", "classnet_1_1minecraft_1_1world_1_1_world_server_multi" ],
    [ "WorldSettings", "classnet_1_1minecraft_1_1world_1_1_world_settings.html", "classnet_1_1minecraft_1_1world_1_1_world_settings" ],
    [ "WorldType", "classnet_1_1minecraft_1_1world_1_1_world_type.html", "classnet_1_1minecraft_1_1world_1_1_world_type" ]
];